# Question and Answer Chat Bots
In this Project we will Build Q&A Chat bots which will study a story and when asked a question will reply in Yes or No according to the situation in the story.

## Data
We will use BaBi dataset of facebook for this project

Full Details: https://research.fb.com/downloads/babi/

## Algorithm 
We will use End-to-End Memory Networks for this project

Full Details: https://arxiv.org/abs/1503.08895

## Now let's load the data and import all the tools needed

In [3]:
import numpy as np
import pickle

C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


### load the training data 

In [4]:
with open("train_qa.txt","rb") as f:
    train_data=pickle.load(f)

In [5]:
train_data[:6]

[(['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.'],
  ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.',
   'Sandra',
   'went',
   'to',
   'the',
   'kitchen',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'bathroom',
   '.'],
  ['Is', 'Daniel', 'in', 'the', '

### load the testing data

In [6]:
with open("test_qa.txt","rb") as f:
    test_data=pickle.load(f)

In [7]:
test_data[:6]

[(['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.',
   'Daniel',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'garden', '?'],
  'yes'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',


In [8]:
len(train_data)

10000

In [9]:
len(test_data)

1000

## Now let's try to grab the story part, question part and answer part from the data

In [10]:
train_data[0]  # This is the first item of the list

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [11]:
train_data[0][0]   # This the story part of the first item

['Mary',
 'moved',
 'to',
 'the',
 'bathroom',
 '.',
 'Sandra',
 'journeyed',
 'to',
 'the',
 'bedroom',
 '.']

In [12]:
" ".join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [13]:
train_data[0][1]   # This is the question part of the first item

['Is', 'Sandra', 'in', 'the', 'hallway', '?']

In [14]:
" ".join(train_data[0][1])

'Is Sandra in the hallway ?'

In [15]:
train_data[0][2]  # This the answer part of the first item

'no'

**Note-** We have only to outcomes as an answer it's either yes or no

### Setting Up Vocabulary of All words

In [16]:
vocab=set()
all_data=train_data + test_data
len(all_data)

11000

In [17]:
for story,ques,ans in all_data: # As each element is sub divided into three section story,question and answer
    vocab=vocab.union(set(story))
    vocab=vocab.union(set(ques))
vocab.add('no')
vocab.add("yes")
len(vocab)

37

In [18]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

### So we have found an vocabulary of 37 words 

In [19]:
vocab_len=len(vocab) +1  # we add 1 to provide an extra space to hold a 0 for keras pad_sequences

In [20]:
max_story_len=max([len(data[0]) for data in all_data])

In [21]:
max_story_len  # So maximum length of a story is 156

156

In [22]:
max_question_len=max([len(data[1]) for data in all_data])
max_question_len    # So maximum length of a question can be 6

6

### Vectorizing the data

In [23]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DELL\Anaconda3\envs\nlp_co

In [24]:
# Create a tokenizer object
tokenizer=Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)
tokenizer.word_index

{'no': 1,
 'the': 2,
 'put': 3,
 'bedroom': 4,
 'hallway': 5,
 'took': 6,
 'journeyed': 7,
 'football': 8,
 'garden': 9,
 'bathroom': 10,
 'picked': 11,
 'to': 12,
 'moved': 13,
 'john': 14,
 'discarded': 15,
 'up': 16,
 'kitchen': 17,
 'dropped': 18,
 'daniel': 19,
 'left': 20,
 'there': 21,
 '.': 22,
 'milk': 23,
 'sandra': 24,
 'down': 25,
 'office': 26,
 'is': 27,
 'travelled': 28,
 'mary': 29,
 'went': 30,
 'yes': 31,
 'grabbed': 32,
 'apple': 33,
 'in': 34,
 '?': 35,
 'back': 36,
 'got': 37}

In [28]:
train_story_text=[]
train_ques_text=[]
train_ans_text=[]

for story,ques,ans in test_data:
    train_story_text.append(story)
    train_ques_text.append(ques)
    train_ans_text.append(ans)

In [29]:
train_story_text[:2]

[['Mary',
  'got',
  'the',
  'milk',
  'there',
  '.',
  'John',
  'moved',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'got',
  'the',
  'milk',
  'there',
  '.',
  'John',
  'moved',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'discarded',
  'the',
  'milk',
  '.',
  'John',
  'went',
  'to',
  'the',
  'garden',
  '.']]

In [30]:
## Let's create a function now for the above functionality
def vectorize_stories(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_question_len=max_question_len):
    # X=stories
    X=[]
    
    # Xq=Question/Query
    Xq=[]
    
    # Y=Correct Answers
    Y=[]
    
    for story,ques,ans in data:
        x=[word_index[word.lower()] for word in story]
        xq=[word_index[word.lower()] for word in ques]
        y=np.zeros(len(word_index) +1)
        y[word_index[ans]]=1
        
        X.append(x)
        Xq.append(xq)
        Y.append(y)
        
    return (pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq,maxlen=max_question_len),np.array(Y))

In [31]:
input_train,ques_train,ans_train=vectorize_stories(train_data)

In [32]:
input_train[:3]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        29, 13, 12,  2, 10, 22, 24,  7, 12,  2,  4, 22],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

In [33]:
ques_train[:3]

array([[27, 24, 34,  2,  5, 35],
       [27, 19, 34,  2, 10, 35],
       [27, 19, 34,  2, 26, 35]])

In [34]:
ans_train[:3]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [35]:
tokenizer.word_index["no"]

1

In [36]:
sum(ans_train)

array([   0., 4988.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0., 5012.,    0.,    0.,    0.,    0.,
          0.,    0.])

In [37]:
input_test,ques_test,ans_test=vectorize_stories(test_data)

In [38]:
input_test.shape

(1000, 156)

In [39]:
input_train.shape

(10000, 156)

## Creating the Model

In [42]:
#import all the tools 
from keras.models import Sequential,Model
from keras.layers.embeddings import Embedding
from keras.layers import add,dot,concatenate
from keras.layers import Activation,Permute,Dense,Dropout,Input
from keras.layers import LSTM

**Placeholders for inputs**

In [43]:
input_sequence=Input((max_story_len,))
question=Input((max_question_len,))

### Building the Networks

### Encoders
Input get embedded to a sequence of vectors

**Input Encoder m**

In [44]:
input_encoder_m=Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_len,output_dim=64))
input_encoder_m.add(Dropout(0.4))
# (samples,max_story_len,embedding_dim)

Instructions for updating:
Colocations handled automatically by placer.


### Input Encoder c

In [46]:
# Embed the input into a sequence of vectors of sixe_query_maxlen
input_encoder_c=Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_len,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.4))
# (samples,story_max_len,question_maxLen)

### Question Encoder

In [47]:
question_encoder=Sequential()
question_encoder.add(Embedding(input_dim=vocab_len,output_dim=64,input_length=max_question_len))
question_encoder.add(Dropout(0.4))
# (samples,question_len,embedding_dim)

### Encode Sequences

In [48]:
# Encode input sequences and questions
input_encoded_m=input_encoder_m(input_sequence)
input_encoded_c=input_encoder_c(input_sequence)
question_encoded=question_encoder(question)

In [49]:
# Shape: (samples,story_max_len,question_max_len)
match=dot([input_encoded_m,question_encoded],axes=(2,2))

In [115]:
input_encoded_m.shape

TensorShape([Dimension(None), Dimension(156), Dimension(64)])

In [116]:
question_encoded.shape

TensorShape([Dimension(None), Dimension(6), Dimension(64)])

In [118]:
match.shape

TensorShape([Dimension(None), Dimension(156), Dimension(6)])

In [120]:
match=Activation("softmax")(match)

In [123]:
# add the matrix with second input vector sequence
response=add([match,input_encoded_c])

In [125]:
#We will permute to alter response dimensions
response=Permute((2,1))(response)

In [126]:
response.shape

TensorShape([Dimension(None), Dimension(6), Dimension(156)])

### Concatenate

In [127]:
# Concatenate the match matrix with question vector sequence
answer=concatenate([response,question_encoded])

In [128]:
answer.shape

TensorShape([Dimension(None), Dimension(6), Dimension(220)])

### Reduce with RNN(LSTM)

In [129]:
answer=LSTM(32)(answer)

In [130]:
answer.shape

TensorShape([Dimension(None), Dimension(32)])

In [132]:
#Regularization with dropout
answer=Dropout(0.5)(answer)
answer=Dense(vocab_len)(answer)

In [133]:
answer=Activation("softmax")(answer)

In [134]:
answer.shape

TensorShape([Dimension(None), Dimension(38)])

### Build the final model

In [135]:
model=Model([input_sequence,question],answer)
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 156)          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 6)            0                                            
__________________________________________________________________________________________________
sequential_1 (Sequential)       multiple             2432        input_1[0][0]                    
__________________________________________________________________________________________________
sequential_3 (Sequential)       (None, 6, 64)        2432        input_2[0][0]                    
____________________________________________________________________________________________

## Now let's open this notebook in google colab to use it's GPU to train the model with high execution speed

## Remaining code after this is in chat_bots_colab jupyter notebook