# Question and Answer Chat Bots
In this Project we will Build Q&A Chat bots which will study a story and when asked a question will reply in Yes or No according to the situation in the story.

## Data
We will use BaBi dataset of facebook for this project

Full Details: https://research.fb.com/downloads/babi/

## Algorithm 
We will use End-to-End Memory Networks for this project

Full Details: https://arxiv.org/abs/1503.08895

## Now let's load the data and import all the tools needed

In [1]:
import numpy as np
import pickle

C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\DELL\Anaconda3\envs\nlp_course\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


### load the training data 

In [2]:
with open("train_qa.txt","rb") as f:
    train_data=pickle.load(f)

In [11]:
train_data[:6]

[(['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.'],
  ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.',
   'Sandra',
   'went',
   'to',
   'the',
   'kitchen',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'bathroom',
   '.'],
  ['Is', 'Daniel', 'in', 'the', '

### load the testing data

In [12]:
with open("test_qa.txt","rb") as f:
    test_data=pickle.load(f)

In [13]:
test_data[:6]

[(['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'kitchen', '?'],
  'no'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'discarded',
   'the',
   'milk',
   '.',
   'John',
   'went',
   'to',
   'the',
   'garden',
   '.',
   'Daniel',
   'moved',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'to',
   'the',
   'garden',
   '.'],
  ['Is', 'John', 'in', 'the', 'garden', '?'],
  'yes'),
 (['Mary',
   'got',
   'the',
   'milk',
   'there',
   '.',
   'John',
   'moved',


In [14]:
len(train_data)

10000

In [15]:
len(test_data)

1000

## Now let's try to grab the story part, question part and answer part from the data

In [16]:
train_data[0]  # This is the first item of the list

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [17]:
train_data[0][0]   # This the story part of the first item

['Mary',
 'moved',
 'to',
 'the',
 'bathroom',
 '.',
 'Sandra',
 'journeyed',
 'to',
 'the',
 'bedroom',
 '.']

In [18]:
" ".join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [19]:
train_data[0][1]   # This is the question part of the first item

['Is', 'Sandra', 'in', 'the', 'hallway', '?']

In [20]:
" ".join(train_data[0][1])

'Is Sandra in the hallway ?'

In [21]:
train_data[0][2]  # This the answer part of the first item

'no'

**Note-** We have only to outcomes as an answer it's either yes or no

### Setting Up Vocabulary of All words

In [22]:
vocab=set()
all_data=train_data + test_data
len(all_data)

11000

In [23]:
for story,ques,ans in all_data: # As each element is sub divided into three section story,question and answer
    vocab=vocab.union(set(story))
    vocab=vocab.union(set(ques))
vocab.add('no')
vocab.add("yes")
len(vocab)

37

In [24]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

### So we have found an vocabulary of 37 words 

In [25]:
vocab_len=len(vocab) +1  # we add 1 to provide an extra space to hold a 0 for keras pad_sequences

In [26]:
max_story_len=max([len(data[0]) for data in all_data])

In [27]:
max_story_len  # So maximum length of a story is 156

156

In [30]:
max_question_len=max([len(data[1]) for data in all_data])
max_question_len    # So maximum length of a question can be 6

6

### Vectorizing the data

In [31]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [33]:
# Create a tokenizer object
tokenizer=Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)
tokenizer.word_index

{'sandra': 1,
 'up': 2,
 'garden': 3,
 'apple': 4,
 'took': 5,
 'the': 6,
 '?': 7,
 'kitchen': 8,
 'went': 9,
 'down': 10,
 'picked': 11,
 'journeyed': 12,
 'to': 13,
 'in': 14,
 'travelled': 15,
 'hallway': 16,
 'there': 17,
 'john': 18,
 'football': 19,
 'put': 20,
 'mary': 21,
 'yes': 22,
 'bathroom': 23,
 '.': 24,
 'left': 25,
 'moved': 26,
 'grabbed': 27,
 'discarded': 28,
 'back': 29,
 'no': 30,
 'milk': 31,
 'dropped': 32,
 'daniel': 33,
 'bedroom': 34,
 'office': 35,
 'got': 36,
 'is': 37}

In [34]:
train_story_text=[]
train_ques_text=[]
train_ans_text=[]

for story,ques,ans in test_data:
    train_story_text.append(story)
    train_ques_text.append(ques)
    train_ans_text.append(ans)

In [36]:
train_story_text[:2]

[['Mary',
  'got',
  'the',
  'milk',
  'there',
  '.',
  'John',
  'moved',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'got',
  'the',
  'milk',
  'there',
  '.',
  'John',
  'moved',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'discarded',
  'the',
  'milk',
  '.',
  'John',
  'went',
  'to',
  'the',
  'garden',
  '.']]

In [43]:
## Let's create a function now for the above functionality
def vectorize_stories(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_question_len=max_question_len):
    # X=stories
    X=[]
    
    # Xq=Question/Query
    Xq=[]
    
    # Y=Correct Answers
    Y=[]
    
    for story,ques,ans in data:
        x=[word_index[word.lower()] for word in story]
        xq=[word_index[word.lower()] for word in ques]
        y=np.zeros(len(word_index) +1)
        y[word_index[ans]]=1
        
        X.append(x)
        Xq.append(xq)
        Y.append(y)
        
    return (pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq,maxlen=max_question_len),np.array(Y))

In [44]:
input_train,ques_train,ans_train=vectorize_stories(train_data)

In [45]:
input_train[:3]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        21, 26, 13,  6, 23, 24,  1, 12, 13,  6, 34, 24],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

In [46]:
ques_train[:3]

array([[37,  1, 14,  6, 16,  7],
       [37, 33, 14,  6, 23,  7],
       [37, 33, 14,  6, 35,  7]])

In [47]:
ans_train[:3]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0.]])

In [50]:
tokenizer.word_index["no"]

30

In [51]:
sum(ans_train)

array([   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0., 5012.,    0.,    0.,    0.,    0.,
          0.,    0.,    0., 4988.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.])

In [52]:
input_test,ques_test,ans_test=vectorize_stories(test_data)

In [53]:
input_test.shape

(1000, 156)

In [54]:
input_train.shape

(10000, 156)